import { useEffect, useMemo, useState } from 'react'
import { LayoutDashboard, Users, Layers, IndianRupee, FileText, MessageCircleQuestion, Bell, Settings, Plus, Share2, Copy, Upload } from 'lucide-react'
import { PortalLayout } from '../components/Layout'
import { Badge, Button, Card, Empty, Input, Select } from '../components/UI'
import { supabase } from '../lib/supabase'

const navItems=[
  {key:'dashboard',label:'Dashboard',icon:LayoutDashboard},{key:'students',label:'Students',icon:Users},{key:'batches',label:'Batches',icon:Layers},{key:'fees',label:'Fees',icon:IndianRupee},{key:'notes',label:'Notes',icon:FileText},{key:'doubts',label:'Doubts',icon:MessageCircleQuestion},{key:'notifications',label:'Notifications',icon:Bell},{key:'settings',label:'Settings',icon:Settings}
]

function Stat({label,value,icon:Icon,tone='blue'}){return <Card className="stat-card"><div><span>{label}</span><strong>{value}</strong></div><i className={tone}><Icon/></i></Card>}

export default function Admin({profile,logout}){
  const [active,setActive]=useState('dashboard')
  const [students,setStudents]=useState([]),[batches,setBatches]=useState([]),[fees,setFees]=useState([]),[notes,setNotes]=useState([]),[doubts,setDoubts]=useState([]),[notifications,setNotifications]=useState([])
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[created,setCreated]=useState(null)
  const [studentForm,setStudentForm]=useState({fullName:'',course:'Boards',classLevel:'12',batchId:'',phone:''})
  const [batchForm,setBatchForm]=useState({name:'',course:'Boards',classLevel:'12'})
  const [feeForm,setFeeForm]=useState({studentId:'',amount:'',month:new Date().toISOString().slice(0,7),status:'due'})
  const [noticeForm,setNoticeForm]=useState({title:'',message:'',audience:'all'})
  const [noteForm,setNoteForm]=useState({title:'',subject:'Chemistry',course:'Boards',classLevel:'12',batchId:'',file:null})
  useEffect(()=>{loadAll()},[])
  async function loadAll(){
    const queries=[['students','created_at'],['batches','created_at'],['fees','created_at'],['notes','created_at'],['doubts','created_at'],['notifications','created_at']]
    const results=await Promise.all(queries.map(([t,o])=>supabase.from(t).select('*').order(o,{ascending:false})))
    ;[setStudents,setBatches,setFees,setNotes,setDoubts,setNotifications].forEach((setter,i)=>setter(results[i].data||[]))
  }
  const totalPending=fees.filter(f=>f.status!=='paid').reduce((s,f)=>s+Number(f.amount||0),0)
  async function createStudent(e){e.preventDefault();setBusy(true);setError('');setCreated(null);try{
    const {data:{session}}=await supabase.auth.getSession()
    const r=await fetch('/api/create-student',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${session.access_token}`},body:JSON.stringify(studentForm)})
    const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not create student');setCreated(d);setStudentForm({fullName:'',course:'Boards',classLevel:'12',batchId:'',phone:''});await loadAll()
  }catch(e){setError(e.message)}finally{setBusy(false)}}
  function credentialMessage(){return `Welcome to The Apex Chemistry!\n\nStudent: ${created.fullName}\nCourse: ${created.course}\nStudent ID: ${created.studentId}\nPassword: ${created.password}\nLogin: ${created.siteUrl}\n\nPlease keep these credentials private.`}
  async function shareCredentials(){const text=credentialMessage();if(navigator.share)await navigator.share({title:'The Apex Chemistry Login',text});else await navigator.clipboard.writeText(text)}
  async function copyCredentials(){await navigator.clipboard.writeText(credentialMessage())}
  async function createBatch(e){e.preventDefault();const {error}=await supabase.from('batches').insert({name:batchForm.name,course:batchForm.course,class_level:batchForm.classLevel});if(error)setError(error.message);else{setBatchForm({name:'',course:'Boards',classLevel:'12'});loadAll()}}
  async function addFee(e){e.preventDefault();const student=students.find(s=>s.student_id===feeForm.studentId);if(!student)return setError('Select a student');const {error}=await supabase.from('fees').insert({student_user_id:student.user_id,student_id:student.student_id,amount:Number(feeForm.amount),month:feeForm.month,status:feeForm.status});if(error)setError(error.message);else{setFeeForm({...feeForm,amount:''});loadAll()}}
  async function sendNotice(e){e.preventDefault();const {error}=await supabase.from('notifications').insert({title:noticeForm.title,message:noticeForm.message,audience:noticeForm.audience,created_by:profile.id});if(error)setError(error.message);else{setNoticeForm({title:'',message:'',audience:'all'});loadAll()}}
  async function uploadNote(e){e.preventDefault();if(!noteForm.file)return setError('Choose a PDF');setBusy(true);setError('');try{const path=`notes/${Date.now()}-${noteForm.file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const {error:upErr}=await supabase.storage.from('apex-chemistry-files').upload(path,noteForm.file,{contentType:noteForm.file.type,upsert:false});if(upErr)throw upErr;const {error:dbErr}=await supabase.from('notes').insert({title:noteForm.title,subject:noteForm.subject,course:noteForm.course,class_level:noteForm.classLevel,batch_id:noteForm.batchId||null,file_path:path,file_name:noteForm.file.name,published:true,created_by:profile.id});if(dbErr)throw dbErr;setNoteForm({title:'',subject:'Chemistry',course:'Boards',classLevel:'12',batchId:'',file:null});loadAll()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function answerDoubt(id){const answer=prompt('Type the answer for this doubt:');if(!answer)return;await supabase.from('doubts').update({answer,status:'answered',answered_at:new Date().toISOString(),answered_by:profile.id}).eq('id',id);loadAll()}
  const recentStudents=students.slice(0,5)
  return <PortalLayout mode="admin" items={navItems} active={active} onSelect={setActive} onLogout={logout} userName={profile.full_name||profile.email}>
    {error&&<div className="error-box">{error}</div>}
    {active==='dashboard'&&<><div className="page-title"><div><h1>Dashboard</h1><p>Welcome back, Administrator!</p></div></div><div className="stats"><Stat label="Total Students" value={students.length} icon={Users}/><Stat label="Total Batches" value={batches.length} icon={Layers} tone="green"/><Stat label="Pending Fees" value={`₹ ${totalPending.toLocaleString('en-IN')}`} icon={IndianRupee} tone="orange"/><Stat label="Total Doubts" value={doubts.length} icon={MessageCircleQuestion} tone="purple"/></div><div className="dashboard-grid"><Card><div className="card-head"><h3>Recent Students</h3><button onClick={()=>setActive('students')}>View all</button></div>{recentStudents.length?<div className="simple-table">{recentStudents.map(s=><div key={s.id}><b>{s.full_name}</b><span>{s.student_id}</span><Badge tone={s.course==='JEE'?'green':s.course==='NEET'?'purple':'blue'}>{s.course}</Badge></div>)}</div>:<Empty title="No students yet"/>}</Card><Card><div className="card-head"><h3>Recent Notifications</h3></div>{notifications.slice(0,4).map(n=><div className="notice-row" key={n.id}><Bell size={18}/><span><b>{n.title}</b><small>{n.message}</small></span></div>)}</Card></div></>}
    {active==='students'&&<><div className="page-title"><div><h1>Students</h1><p>Create and manage registered students.</p></div></div><div className="split-grid"><Card><h3>Create Student</h3><form className="form-grid" onSubmit={createStudent}><Input label="Full Name" value={studentForm.fullName} onChange={e=>setStudentForm({...studentForm,fullName:e.target.value})} required/><Select label="Course" value={studentForm.course} onChange={e=>setStudentForm({...studentForm,course:e.target.value})}><option>JEE</option><option>NEET</option><option>Boards</option></Select><Select label="Class" value={studentForm.classLevel} onChange={e=>setStudentForm({...studentForm,classLevel:e.target.value})}><option>11</option><option>12</option></Select><Select label="Batch" value={studentForm.batchId} onChange={e=>setStudentForm({...studentForm,batchId:e.target.value})}><option value="">No batch</option>{batches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</Select><Input label="Phone" value={studentForm.phone} onChange={e=>setStudentForm({...studentForm,phone:e.target.value})}/><Button disabled={busy}><Plus size={17}/>{busy?'Creating…':'Create Student'}</Button></form></Card>{created&&<Card className="success-card"><h3>Student Created Successfully 🎉</h3><p>{created.fullName} • {created.course}</p><div className="credential"><span>Student ID</span><b>{created.studentId}</b></div><div className="credential"><span>Password</span><b>{created.password}</b></div><div className="button-row"><Button variant="success" onClick={shareCredentials}><Share2 size={17}/>Share Credentials</Button><Button variant="outline" onClick={copyCredentials}><Copy size={17}/>Copy Message</Button></div></Card>}</div><Card><div className="table"><div className="tr th"><span>Name</span><span>Student ID</span><span>Course</span><span>Class</span><span>Phone</span></div>{students.map(s=><div className="tr" key={s.id}><span><b>{s.full_name}</b></span><span>{s.student_id}</span><span><Badge>{s.course}</Badge></span><span>{s.class_level}</span><span>{s.phone||'—'}</span></div>)}</div></Card></>}
    {active==='batches'&&<><div className="page-title"><div><h1>Batches</h1><p>Organize learners into teaching groups.</p></div></div><Card><form className="inline-form" onSubmit={createBatch}><Input label="Batch Name" value={batchForm.name} onChange={e=>setBatchForm({...batchForm,name:e.target.value})} required/><Select label="Course" value={batchForm.course} onChange={e=>setBatchForm({...batchForm,course:e.target.value})}><option>JEE</option><option>NEET</option><option>Boards</option></Select><Select label="Class" value={batchForm.classLevel} onChange={e=>setBatchForm({...batchForm,classLevel:e.target.value})}><option>11</option><option>12</option></Select><Button>Add Batch</Button></form></Card><div className="cards-grid">{batches.map(b=><Card key={b.id}><Badge>{b.course}</Badge><h3>{b.name}</h3><p>Class {b.class_level}</p></Card>)}</div></>}
    {active==='fees'&&<><div className="page-title"><div><h1>Fees</h1><p>Record and monitor student payments.</p></div></div><Card><form className="inline-form" onSubmit={addFee}><Select label="Student" value={feeForm.studentId} onChange={e=>setFeeForm({...feeForm,studentId:e.target.value})}><option value="">Select student</option>{students.map(s=><option key={s.id}>{s.student_id}</option>)}</Select><Input label="Amount" type="number" value={feeForm.amount} onChange={e=>setFeeForm({...feeForm,amount:e.target.value})} required/><Input label="Month" type="month" value={feeForm.month} onChange={e=>setFeeForm({...feeForm,month:e.target.value})}/><Select label="Status" value={feeForm.status} onChange={e=>setFeeForm({...feeForm,status:e.target.value})}><option value="due">Due</option><option value="paid">Paid</option><option value="partial">Partial</option></Select><Button>Save Fee</Button></form></Card><Card><div className="table"><div className="tr th"><span>Student</span><span>Month</span><span>Amount</span><span>Status</span><span>Date</span></div>{fees.map(f=><div className="tr" key={f.id}><span>{f.student_id}</span><span>{f.month}</span><span>₹ {Number(f.amount).toLocaleString('en-IN')}</span><span><Badge tone={f.status==='paid'?'green':'orange'}>{f.status}</Badge></span><span>{new Date(f.created_at).toLocaleDateString()}</span></div>)}</div></Card></>}
    {active==='notes'&&<><div className="page-title"><div><h1>Notes</h1><p>Upload private PDF study material.</p></div></div><Card><form className="form-grid" onSubmit={uploadNote}><Input label="Title" value={noteForm.title} onChange={e=>setNoteForm({...noteForm,title:e.target.value})} required/><Input label="Subject" value={noteForm.subject} onChange={e=>setNoteForm({...noteForm,subject:e.target.value})}/><Select label="Course" value={noteForm.course} onChange={e=>setNoteForm({...noteForm,course:e.target.value})}><option>JEE</option><option>NEET</option><option>Boards</option></Select><Select label="Class" value={noteForm.classLevel} onChange={e=>setNoteForm({...noteForm,classLevel:e.target.value})}><option>11</option><option>12</option></Select><label className="field"><span>PDF File</span><input type="file" accept="application/pdf" onChange={e=>setNoteForm({...noteForm,file:e.target.files?.[0]})} required/></label><Button disabled={busy}><Upload size={17}/>Upload Note</Button></form></Card><div className="cards-grid">{notes.map(n=><Card key={n.id}><Badge>{n.course}</Badge><h3>{n.title}</h3><p>{n.subject} • Class {n.class_level}</p></Card>)}</div></>}
    {active==='doubts'&&<><div className="page-title"><div><h1>Doubts</h1><p>Answer questions submitted by students.</p></div></div><div className="cards-grid">{doubts.length?doubts.map(d=><Card key={d.id}><div className="card-head"><Badge tone={d.status==='answered'?'green':'orange'}>{d.status}</Badge><small>{d.student_id}</small></div><h3>{d.question}</h3><p>{d.subject}</p>{d.answer&&<div className="answer">{d.answer}</div>}{d.status!=='answered'&&<Button onClick={()=>answerDoubt(d.id)}>Answer</Button>}</Card>):<Empty/>}</div></>}
    {active==='notifications'&&<><div className="page-title"><div><h1>Notifications</h1><p>Send announcements to students.</p></div></div><Card><form className="form-grid" onSubmit={sendNotice}><Input label="Title" value={noticeForm.title} onChange={e=>setNoticeForm({...noticeForm,title:e.target.value})} required/><Input label="Message" value={noticeForm.message} onChange={e=>setNoticeForm({...noticeForm,message:e.target.value})} required/><Select label="Audience" value={noticeForm.audience} onChange={e=>setNoticeForm({...noticeForm,audience:e.target.value})}><option value="all">All students</option><option value="JEE">JEE</option><option value="NEET">NEET</option><option value="Boards">Boards</option></Select><Button>Publish</Button></form></Card><div className="cards-grid">{notifications.map(n=><Card key={n.id}><Badge>{n.audience}</Badge><h3>{n.title}</h3><p>{n.message}</p></Card>)}</div></>}
    {active==='settings'&&<Card><h2>Supabase + Netlify</h2><p>This portal uses Supabase Authentication, PostgreSQL, Row Level Security and private Storage. Server-only administration runs through Netlify Functions.</p><p><b>Signed in as:</b> {profile.email}</p></Card>}
  </PortalLayout>
}
