import React, { useEffect, useState } from 'react'
import { Routes, Route, useLocation } from 'react-router-dom'
import { collection, addDoc, doc, onSnapshot, orderBy, query, serverTimestamp, where } from 'firebase/firestore'
import { Bell, BookOpen, CalendarDays, IndianRupee, LayoutDashboard, MessageCircleQuestion } from 'lucide-react'
import Layout from '../components/Layout'
import { Badge, Button, Card, Empty, Input } from '../components/ui'
import { db } from '../lib/firebase'
import { api } from '../lib/api'

const nav=[{to:'/student',label:'Dashboard',icon:LayoutDashboard},{to:'/student/notes',label:'Notes',icon:BookOpen},{to:'/student/fees',label:'Fees',icon:IndianRupee},{to:'/student/notifications',label:'Notifications',icon:Bell},{to:'/student/doubts',label:'Ask a doubt',icon:MessageCircleQuestion},{to:'/student/calendar',label:'Calendar',icon:CalendarDays}]
function useMine(name,uid){const [items,setItems]=useState([]);useEffect(()=>{if(!uid)return;const q=query(collection(db,name),orderBy('createdAt','desc'));return onSnapshot(q,s=>setItems(s.docs.map(d=>({id:d.id,...d.data()}))))},[name,uid]);return items}
export default function Student({user,profile}){const location=useLocation();const [mobileOpen,setMobileOpen]=useState(false);const title=nav.find(n=>n.to===location.pathname)?.label||'Student portal';return <Layout portal="student" title={title} nav={nav} user={{...user,displayName:profile?.name}} mobileOpen={mobileOpen} setMobileOpen={setMobileOpen}><Routes><Route index element={<Dashboard user={user} profile={profile}/>}/><Route path="notes" element={<Notes user={user} profile={profile}/>}/><Route path="fees" element={<Fees user={user}/>}/><Route path="notifications" element={<Notifications profile={profile}/>}/><Route path="doubts" element={<Doubts user={user} profile={profile}/>}/><Route path="calendar" element={<Calendar/>}/></Routes></Layout>}
function Dashboard({user,profile}){const fees=useMine('fees',user.uid).filter(f=>f.studentUid===user.uid);const due=fees.filter(f=>f.status!=='paid').reduce((a,f)=>a+Number(f.amount||0),0);return <><div className="hero-card"><div><span>STUDENT PORTAL</span><h2>Hello, {profile?.name||'Student'}!</h2><p>Stay updated with your classes, notes, fees and teacher responses.</p></div><img src="/icon-192.png"/></div><div className="stats-grid"><Card className="stat"><span>Student ID</span><strong>{profile?.studentId||'—'}</strong></Card><Card className="stat"><span>Class</span><strong>{profile?.classLevel||'—'}</strong></Card><Card className="stat"><span>Batch</span><strong>{profile?.batch||'—'}</strong></Card><Card className="stat"><span>Fees due</span><strong>₹{due.toLocaleString('en-IN')}</strong></Card></div><Card><h3>Your learning space</h3><p className="muted">Download the latest notes, check announcements, track fee status and submit chemistry doubts directly to your teacher.</p></Card></>}
function Notes({user,profile}){const items=useMine('notes',user.uid).filter(n=>['all',user.uid,profile?.classLevel].includes(n.audience));async function open(n){try{const {url}=await api('/api/storage/sign-download',{method:'POST',body:JSON.stringify({path:n.path})});window.open(url,'_blank','noopener')}catch(e){alert(e.message)}}return <div className="card-grid">{items.map(n=><Card key={n.id}><BookOpen size={27}/><h3>{n.title}</h3><p>{n.fileName}</p><Button onClick={()=>open(n)}>Open PDF</Button></Card>)}{!items.length&&<Empty>No notes available yet.</Empty>}</div>}
function Fees({user}){const items=useMine('fees',user.uid).filter(f=>f.studentUid===user.uid);return <Card><div className="table-wrap"><table><thead><tr><th>Month</th><th>Amount</th><th>Status</th></tr></thead><tbody>{items.map(f=><tr key={f.id}><td>{f.month}</td><td>₹{Number(f.amount||0).toLocaleString('en-IN')}</td><td><Badge tone={f.status==='paid'?'success':'warning'}>{f.status}</Badge></td></tr>)}</tbody></table>{!items.length&&<Empty>No fee records.</Empty>}</div></Card>}
function Notifications({profile}){const [items,setItems]=useState([]);useEffect(()=>onSnapshot(query(collection(db,'notifications'),orderBy('createdAt','desc')),s=>setItems(s.docs.map(d=>({id:d.id,...d.data()})).filter(n=>['all',profile?.classLevel].includes(n.audience)))),[profile?.classLevel]);return <div className="list">{items.map(n=><Card key={n.id}><h3>{n.title}</h3><p>{n.message}</p></Card>)}{!items.length&&<Empty>No announcements.</Empty>}</div>}
function Doubts({user,profile}){const items=useMine('doubts',user.uid).filter(d=>d.studentUid===user.uid);const [question,setQuestion]=useState('');const [subject,setSubject]=useState('Chemistry');async function submit(e){e.preventDefault();await addDoc(collection(db,'doubts'),{studentUid:user.uid,studentName:profile?.name||'',subject,question,status:'open',createdAt:serverTimestamp()});setQuestion('')}return <div className="two-col"><Card><h3>Submit a doubt</h3><form onSubmit={submit}><Input label="Topic" value={subject} onChange={e=>setSubject(e.target.value)} required/><label className="field"><span>Your question</span><textarea rows="6" value={question} onChange={e=>setQuestion(e.target.value)} required/></label><Button type="submit">Send to teacher</Button></form></Card><div className="list">{items.map(d=><Card key={d.id}><div className="row-between"><b>{d.subject}</b><Badge tone={d.status==='resolved'?'success':'warning'}>{d.status}</Badge></div><p>{d.question}</p>{d.answer&&<div className="answer"><b>Teacher’s response</b><p>{d.answer}</p></div>}</Card>)}{!items.length&&<Empty>No doubts submitted.</Empty>}</div></div>}
function Calendar(){const today=new Date();const days=new Date(today.getFullYear(),today.getMonth()+1,0).getDate();const first=new Date(today.getFullYear(),today.getMonth(),1).getDay();return <Card><h3>{today.toLocaleString('en-IN',{month:'long',year:'numeric'})}</h3><div className="calendar"><div>Sun</div><div>Mon</div><div>Tue</div><div>Wed</div><div>Thu</div><div>Fri</div><div>Sat</div>{Array(first).fill(0).map((_,i)=><span key={`e${i}`}/>) }{Array.from({length:days},(_,i)=>i+1).map(d=><span className={d===today.getDate()?'today':''} key={d}>{d}</span>)}</div></Card>}
