import React from 'react';
import { onAuthStateChanged, signInWithEmailAndPassword, signOut } from 'firebase/auth';
import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, onSnapshot, orderBy, query, serverTimestamp, setDoc, updateDoc, where, writeBatch } from 'firebase/firestore';
import { LayoutDashboard, Users, Layers3, IndianRupee, Bell, BookOpen, MessageCircleQuestion, CalendarDays, ReceiptIndianRupee, Upload, Plus, Search, CheckCircle2, Clock3, Trash2, Share2, Copy, ExternalLink } from 'lucide-react';
import { auth, db, ADMIN_UID, clientConfigError } from './lib/firebase';
import { supabase, supabaseClientError, bucket } from './lib/supabase';
import { api } from './lib/api';
import { months, money, studentEmail, safeName, dateText } from './lib/utils';
import Layout from './components/Layout';
import { Card, Button, Field, Select, Textarea, Empty, Toast } from './components/UI';

const adminItems=[
 {id:'dashboard',label:'Dashboard',icon:LayoutDashboard},{id:'students',label:'Students',icon:Users},{id:'batches',label:'Batches',icon:Layers3},{id:'fees',label:'Fee Records',icon:IndianRupee},{id:'notes',label:'Notes',icon:BookOpen},{id:'notifications',label:'Notifications',icon:Bell},{id:'doubts',label:'Doubts',icon:MessageCircleQuestion}
];
const studentItems=[
 {id:'dashboard',label:'Dashboard',icon:LayoutDashboard},{id:'calendar',label:'Calendar',icon:CalendarDays},{id:'fees',label:'My Fees',icon:ReceiptIndianRupee},{id:'notes',label:'Notes',icon:BookOpen},{id:'notifications',label:'Notifications',icon:Bell},{id:'doubts',label:'Ask a Doubt',icon:MessageCircleQuestion}
];
function useLive(q){const [rows,setRows]=React.useState([]);React.useEffect(()=>{if(!q)return;return onSnapshot(q,s=>setRows(s.docs.map(d=>({id:d.id,...d.data()}))),e=>console.error(e));},[q]);return rows}
function Login(){
 const [role,setRole]=React.useState('student'),[identifier,setIdentifier]=React.useState(''),[password,setPassword]=React.useState(''),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{if(clientConfigError)throw new Error(clientConfigError);const email=role==='student'?studentEmail(identifier):identifier.trim();const c=await signInWithEmailAndPassword(auth,email,password);if(role==='admin'&&c.user.uid!==ADMIN_UID){await signOut(auth);throw new Error('This account is not the administrator.');}if(role==='student'&&c.user.uid===ADMIN_UID){await signOut(auth);throw new Error('Use the Admin login tab for this account.');}}catch(e){setError(e.message.replace('Firebase: ',''));}finally{setBusy(false)}}
 return <div className="login-page"><div className="login-art"><div className="orb one"/><div className="orb two"/><div className="hero-copy"><span>THE APEX CHEMISTRY</span><h1>Learning becomes clearer when everything is organised.</h1><p>A secure classroom portal for notes, fees, batches, notifications and doubt support.</p></div></div><form className="login-card" onSubmit={submit}><div className="login-logo">A</div><h2>Welcome back</h2><p>Sign in to your portal</p><div className="role-tabs"><button type="button" className={role==='student'?'active':''} onClick={()=>setRole('student')}>Student</button><button type="button" className={role==='admin'?'active':''} onClick={()=>setRole('admin')}>Admin</button></div><Field label={role==='student'?'Student ID':'Admin email'} value={identifier} onChange={e=>setIdentifier(e.target.value)} required autoComplete="username"/><Field label="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/>{error&&<div className="error-box">{error}</div>}<Button disabled={busy}>{busy?'Signing in…':'Sign in securely'}</Button><small className="login-help">Student credentials are created and shared by the administrator.</small></form></div>
}
function App(){
 const [user,setUser]=React.useState(undefined),[profile,setProfile]=React.useState(null),[tab,setTab]=React.useState('dashboard'),[toast,setToast]=React.useState(null);
 React.useEffect(()=>onAuthStateChanged(auth,async u=>{setUser(u||null);setProfile(null);setTab('dashboard');if(u&&u.uid!==ADMIN_UID){const snap=await getDoc(doc(db,'students',u.uid));if(snap.exists())setProfile({id:snap.id,...snap.data()});}}),[]);
 if(user===undefined)return <div className="loading">Loading The Apex Chemistry…</div>;
 if(!user)return <Login/>;
 const admin=user.uid===ADMIN_UID; if(!admin&&!profile)return <div className="loading">Student profile not found. Ask the administrator to recreate your account. <button onClick={()=>signOut(auth)}>Sign out</button></div>;
 return <><Layout role={admin?'Administrator':'Student'} tab={tab} setTab={setTab} onLogout={()=>signOut(auth)} items={admin?adminItems:studentItems} userName={admin?(user.displayName||'Administrator'):profile?.name}>{admin?<AdminPortal tab={tab} notify={setToast}/>:<StudentPortal tab={tab} profile={profile} notify={setToast}/>}</Layout><Toast message={toast} onClose={()=>setToast(null)}/></>
}
function AdminPortal({tab,notify}){
 const batches=useLive(React.useMemo(()=>query(collection(db,'batches'),orderBy('name')),[]));
 const students=useLive(React.useMemo(()=>query(collection(db,'students'),orderBy('name')),[]));
 const fees=useLive(React.useMemo(()=>query(collection(db,'fees'),orderBy('monthKey','desc')),[]));
 const notes=useLive(React.useMemo(()=>query(collection(db,'notes'),orderBy('createdAt','desc')),[]));
 const doubts=useLive(React.useMemo(()=>query(collection(db,'doubts'),orderBy('createdAt','desc')),[]));
 const notifications=useLive(React.useMemo(()=>query(collection(db,'notifications'),orderBy('createdAt','desc')),[]));
 const props={batches,students,fees,notes,doubts,notifications,notify};
 if(tab==='students')return <Students {...props}/>;if(tab==='batches')return <Batches {...props}/>;if(tab==='fees')return <FeesAdmin {...props}/>;if(tab==='notes')return <NotesAdmin {...props}/>;if(tab==='notifications')return <NotificationsAdmin {...props}/>;if(tab==='doubts')return <DoubtsAdmin {...props}/>;
 const paid=fees.filter(f=>f.status==='paid').reduce((a,f)=>a+Number(f.amount||0),0),due=fees.filter(f=>f.status==='due').reduce((a,f)=>a+Number(f.amount||0),0);
 return <><div className="stats"><Stat label="Total earnings" value={money(paid)} icon={IndianRupee}/><Stat label="Outstanding fees" value={money(due)} icon={Clock3}/><Stat label="Students" value={students.length} icon={Users}/><Stat label="Batches" value={batches.length} icon={Layers3}/></div><div className="grid-2"><Card><h3>Recent doubts</h3>{doubts.slice(0,5).map(d=><div className="list-row" key={d.id}><div><strong>{d.studentName}</strong><small>{d.description}</small></div><span className={`pill ${d.status}`}>{d.status}</span></div>)}{!doubts.length&&<Empty>No doubts received.</Empty>}</Card><Card><h3>Latest notes</h3>{notes.slice(0,5).map(n=><div className="list-row" key={n.id}><div><strong>{n.title}</strong><small>{n.batchName}</small></div><BookOpen size={18}/></div>)}{!notes.length&&<Empty>No notes uploaded.</Empty>}</Card></div></>
}
function Stat({label,value,icon:Icon}){return <Card className="stat"><div><small>{label}</small><strong>{value}</strong></div><span><Icon/></span></Card>}
function Batches({batches,students,notify}){
 const empty={name:'',timing:'',fee:'',days:''};const [form,setForm]=React.useState(empty),[busy,setBusy]=React.useState(false);
 async function save(e){e.preventDefault();setBusy(true);try{await addDoc(collection(db,'batches'),{...form,fee:Number(form.fee),createdAt:serverTimestamp(),updatedAt:serverTimestamp()});setForm(empty);notify({type:'success',text:'Batch created.'})}catch(e){notify({type:'error',text:e.message})}finally{setBusy(false)}}
 return <div className="grid-form"><Card><h3>Create batch</h3><form onSubmit={save} className="form-grid"><Field label="Batch name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><Field label="Timing" value={form.timing} onChange={e=>setForm({...form,timing:e.target.value})} placeholder="4:00 PM – 6:00 PM" required/><Field label="Monthly fee" type="number" min="0" value={form.fee} onChange={e=>setForm({...form,fee:e.target.value})} required/><Field label="Days" value={form.days} onChange={e=>setForm({...form,days:e.target.value})} placeholder="Mon, Wed, Fri" required/><Button disabled={busy}>{busy?'Saving…':'Create batch'}</Button></form></Card><Card><h3>Existing batches</h3>{batches.map(b=><div className="batch-card" key={b.id}><div><strong>{b.name}</strong><small>{b.days} · {b.timing}</small></div><div><b>{money(b.fee)}</b><small>{students.filter(s=>s.batchId===b.id).length} students</small></div><button className="icon-btn danger" onClick={async()=>{if(confirm('Delete this batch?'))await deleteDoc(doc(db,'batches',b.id))}}><Trash2 size={17}/></button></div>)}{!batches.length&&<Empty>Create your first batch.</Empty>}</Card></div>
}
function Students({batches,students,notify}){
 const empty={name:'',studentId:'',password:'',batchId:'',phone:'',guardian:'',monthlyFee:''};const [form,setForm]=React.useState(empty),[busy,setBusy]=React.useState(false),[created,setCreated]=React.useState(null),[search,setSearch]=React.useState(''),[filter,setFilter]=React.useState('');
 async function create(e){e.preventDefault();setBusy(true);try{const data=await api('/api/admin/create-student',{method:'POST',body:JSON.stringify(form)});setCreated(data);setForm(empty);notify({type:'success',text:'Student account created.'})}catch(e){notify({type:'error',text:e.message})}finally{setBusy(false)}}
 const visible=students.filter(s=>(!filter||s.batchId===filter)&&(`${s.name} ${s.studentId}`.toLowerCase().includes(search.toLowerCase())));
 const shareText=created&&`The Apex Chemistry\nStudent: ${created.name}\nStudent ID: ${created.studentId}\nPassword: ${created.password}\nWebsite: ${location.origin}`;
 async function share(){if(navigator.share)await navigator.share({title:'The Apex Chemistry credentials',text:shareText});else{await navigator.clipboard.writeText(shareText);notify({type:'success',text:'Credentials copied.'})}}
 return <><div className="grid-form"><Card><h3>Add student</h3><form onSubmit={create} className="form-grid"><Field label="Student name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><Field label="Student ID" value={form.studentId} onChange={e=>setForm({...form,studentId:e.target.value.toUpperCase()})} placeholder="APEX26001" required/><Field label="Temporary password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} minLength="6" required/><Select label="Batch" value={form.batchId} onChange={e=>{const b=batches.find(x=>x.id===e.target.value);setForm({...form,batchId:e.target.value,monthlyFee:b?.fee||''})}} required><option value="">Select batch</option>{batches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</Select><Field label="Monthly fee" type="number" value={form.monthlyFee} onChange={e=>setForm({...form,monthlyFee:e.target.value})}/><Field label="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><Field label="Guardian" value={form.guardian} onChange={e=>setForm({...form,guardian:e.target.value})}/><Button disabled={busy||!batches.length}>{busy?'Creating account…':'Create student'}</Button>{!batches.length&&<small className="warn">Create a batch first.</small>}</form></Card>{created&&<Card className="credential-card"><CheckCircle2 size={38}/><h3>Account ready</h3><p><b>Student ID:</b> {created.studentId}</p><p><b>Password:</b> {created.password}</p><p><b>Website:</b> {location.origin}</p><div className="button-row"><Button onClick={()=>navigator.clipboard.writeText(shareText)} type="button"><Copy size={17}/> Copy</Button><Button onClick={share} type="button" variant="secondary"><Share2 size={17}/> Share</Button></div></Card>}</div><Card><div className="toolbar"><div className="search"><Search size={18}/><input placeholder="Search students" value={search} onChange={e=>setSearch(e.target.value)}/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All batches</option>{batches.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>Student</th><th>ID</th><th>Batch</th><th>Fee</th><th>Status</th><th/></tr></thead><tbody>{visible.map(s=><tr key={s.id}><td><strong>{s.name}</strong><small>{s.phone||'No phone'}</small></td><td>{s.studentId}</td><td>{s.batchName}</td><td>{money(s.monthlyFee)}</td><td><span className={`pill ${s.status}`}>{s.status}</span></td><td><button className="icon-btn danger" onClick={async()=>{if(confirm(`Delete ${s.name}?`)){try{await api('/api/admin/delete-student',{method:'POST',body:JSON.stringify({uid:s.id})});notify({type:'success',text:'Student deleted.'})}catch(e){notify({type:'error',text:e.message})}}}}><Trash2 size={17}/></button></td></tr>)}</tbody></table>{!visible.length&&<Empty>No matching students.</Empty>}</div></Card></>
}
function FeesAdmin({batches,students,fees,notify}){const [batchId,setBatchId]=React.useState(''),year=new Date().getFullYear();const selected=students.filter(s=>s.batchId===batchId);async function setStatus(student,month,status){const id=`${student.id}_${year}-${String(month).padStart(2,'0')}`;await setDoc(doc(db,'fees',id),{studentUid:student.id,studentId:student.studentId,studentName:student.name,batchId:student.batchId,year,month,monthKey:`${year}-${String(month).padStart(2,'0')}`,amount:Number(student.monthlyFee||0),status,paidAt:status==='paid'?serverTimestamp():null,updatedAt:serverTimestamp(),createdAt:serverTimestamp()},{merge:true});notify({type:'success',text:`Fee marked ${status}.`})}
 return <><Card><Select label="Select batch" value={batchId} onChange={e=>setBatchId(e.target.value)}><option value="">Choose a batch</option>{batches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</Select></Card>{selected.map(s=><Card key={s.id}><div className="section-title"><div><h3>{s.name}</h3><p>{s.studentId} · {money(s.monthlyFee)} monthly</p></div></div><div className="months-grid">{months.map((m,i)=>{const f=fees.find(x=>x.studentUid===s.id&&x.year===year&&x.month===i+1);const future=i+1>new Date().getMonth()+1&&!f;const status=f?.status||(future?'upcoming':'due');return <div className="month" key={m}><strong>{m.slice(0,3)}</strong><span className={`pill ${status}`}>{status}</span><small>{money(f?.amount||s.monthlyFee)}</small><div><button onClick={()=>setStatus(s,i+1,'paid')} title="Mark paid"><CheckCircle2 size={16}/></button><button onClick={()=>setStatus(s,i+1,'due')} title="Mark due"><Clock3 size={16}/></button></div></div>})}</div></Card>)}{batchId&&!selected.length&&<Empty>No students in this batch.</Empty>}</>
}
function NotesAdmin({batches,notes,notify}){const [title,setTitle]=React.useState(''),[batchId,setBatchId]=React.useState(''),[file,setFile]=React.useState(null),[busy,setBusy]=React.useState(false);async function upload(e){e.preventDefault();setBusy(true);try{if(!supabase)throw new Error(supabaseClientError);const b=batches.find(x=>x.id===batchId);const signed=await api('/api/storage/sign-upload',{method:'POST',body:JSON.stringify({fileName:file.name,mimeType:file.type,size:file.size,type:'note',batchId})});const {error}=await supabase.storage.from(bucket).uploadToSignedUrl(signed.path,signed.token,file,{contentType:file.type,upsert:false});if(error)throw new Error(error.message);await addDoc(collection(db,'notes'),{title,batchId,batchName:b.name,fileName:file.name,filePath:signed.path,fileSize:file.size,mimeType:file.type,createdAt:serverTimestamp()});setTitle('');setBatchId('');setFile(null);e.target.reset();notify({type:'success',text:'PDF uploaded successfully.'})}catch(e){notify({type:'error',text:e.message})}finally{setBusy(false)}}
 return <div className="grid-form"><Card><h3>Upload PDF note</h3><form onSubmit={upload} className="form-grid"><Field label="Title" value={title} onChange={e=>setTitle(e.target.value)} required/><Select label="Batch" value={batchId} onChange={e=>setBatchId(e.target.value)} required><option value="">Select batch</option>{batches.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</Select><label className="upload-box"><Upload/><span>{file?.name||'Choose PDF (maximum 20 MB)'}</span><input type="file" accept="application/pdf" onChange={e=>setFile(e.target.files[0])} required/></label><Button disabled={busy}>{busy?'Uploading…':'Upload note'}</Button></form></Card><Card><h3>Uploaded notes</h3>{notes.map(n=><div className="list-row" key={n.id}><div><strong>{n.title}</strong><small>{n.batchName} · {n.fileName}</small></div><button className="icon-btn danger" onClick={async()=>{if(confirm('Delete this note?')){try{await api('/api/storage/delete',{method:'POST',body:JSON.stringify({path:n.filePath})});await deleteDoc(doc(db,'notes',n.id))}catch(e){notify({type:'error',text:e.message})}}}}><Trash2 size={17}/></button></div>)}{!notes.length&&<Empty>No notes uploaded.</Empty>}</Card></div>}
function NotificationsAdmin({batches,students,notifications,notify}){const [target,setTarget]=React.useState('batch'),[targetId,setTargetId]=React.useState(''),[title,setTitle]=React.useState(''),[message,setMessage]=React.useState(''),[busy,setBusy]=React.useState(false);async function send(e){e.preventDefault();setBusy(true);try{const recipients=target==='batch'?students.filter(s=>s.batchId===targetId):students.filter(s=>s.id===targetId);if(!recipients.length)throw new Error('No recipients selected.');const wb=writeBatch(db);recipients.forEach(s=>wb.set(doc(collection(db,'notifications')),{studentUid:s.id,title,message,type:'announcement',read:false,createdAt:serverTimestamp()}));await wb.commit();setTitle('');setMessage('');notify({type:'success',text:`Notification sent to ${recipients.length} student(s).`})}catch(e){notify({type:'error',text:e.message})}finally{setBusy(false)}}return <div className="grid-form"><Card><h3>Send notification</h3><form onSubmit={send} className="form-grid"><Select label="Send to" value={target} onChange={e=>{setTarget(e.target.value);setTargetId('')}}><option value="batch">Entire batch</option><option value="student">Single student</option></Select><Select label={target==='batch'?'Batch':'Student'} value={targetId} onChange={e=>setTargetId(e.target.value)} required><option value="">Select</option>{(target==='batch'?batches:students).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><Field label="Title" value={title} onChange={e=>setTitle(e.target.value)} required/><Textarea label="Message" rows="5" value={message} onChange={e=>setMessage(e.target.value)} required/><Button disabled={busy}>{busy?'Sending…':'Send notification'}</Button></form></Card><Card><h3>Recent activity</h3>{notifications.slice(0,20).map(n=><div className="list-row" key={n.id}><div><strong>{n.title}</strong><small>{n.message}</small></div><small>{dateText(n.createdAt)}</small></div>)}{!notifications.length&&<Empty>No notifications yet.</Empty>}</Card></div>}
function DoubtsAdmin({doubts,notify}){const [answer,setAnswer]=React.useState({});async function submit(d){const text=answer[d.id]?.trim();if(!text)return;try{await updateDoc(doc(db,'doubts',d.id),{answer:text,status:'answered',answeredAt:serverTimestamp(),updatedAt:serverTimestamp()});await addDoc(collection(db,'notifications'),{studentUid:d.studentUid,title:'Your doubt was answered',message:text,type:'doubt_answer',read:false,createdAt:serverTimestamp()});setAnswer({...answer,[d.id]:''});notify({type:'success',text:'Answer sent.'})}catch(e){notify({type:'error',text:e.message})}}return <div className="cards-list">{doubts.map(d=><Card key={d.id}><div className="section-title"><div><h3>{d.studentName}</h3><p>{d.batchName} · {dateText(d.createdAt)}</p></div><span className={`pill ${d.status}`}>{d.status}</span></div><p className="question">{d.description}</p>{d.imagePath&&<DoubtImage doubt={d}/>} {d.answer&&<div className="answer"><b>Answer:</b> {d.answer}</div>}<div className="answer-form"><textarea placeholder="Write an explanation…" value={answer[d.id]||''} onChange={e=>setAnswer({...answer,[d.id]:e.target.value})}/><Button onClick={()=>submit(d)}>Send answer</Button></div></Card>)}{!doubts.length&&<Empty>No doubts received.</Empty>}</div>}
function DoubtImage({doubt}){const [url,setUrl]=React.useState('');React.useEffect(()=>{api('/api/storage/sign-download',{method:'POST',body:JSON.stringify({path:doubt.imagePath})}).then(x=>setUrl(x.url)).catch(()=>{})},[doubt.imagePath]);return url?<a href={url} target="_blank" rel="noreferrer"><img className="doubt-image" src={url}/></a>:null}
function StudentPortal({tab,profile,notify}){const uid=profile.id;const fees=useLive(React.useMemo(()=>query(collection(db,'fees'),where('studentUid','==',uid)),[uid]));const notes=useLive(React.useMemo(()=>query(collection(db,'notes'),where('batchId','==',profile.batchId)),[profile.batchId]));const notifications=useLive(React.useMemo(()=>query(collection(db,'notifications'),where('studentUid','==',uid)),[uid]));const doubts=useLive(React.useMemo(()=>query(collection(db,'doubts'),where('studentUid','==',uid)),[uid]));
 if(tab==='fees')return <StudentFees fees={fees} profile={profile}/>;if(tab==='notes')return <StudentNotes notes={notes} notify={notify}/>;if(tab==='notifications')return <StudentNotifications notifications={notifications}/>;if(tab==='doubts')return <StudentDoubts profile={profile} doubts={doubts} notify={notify}/>;if(tab==='calendar')return <Calendar profile={profile}/>;
 const due=fees.filter(f=>f.status==='due').reduce((a,f)=>a+Number(f.amount||0),0);return <><div className="welcome"><div><span>Welcome back</span><h2>{profile.name}</h2><p>{profile.batchName} · {profile.studentId}</p></div><div className="atom">⚛</div></div><div className="stats"><Stat label="Monthly fee" value={money(profile.monthlyFee)} icon={IndianRupee}/><Stat label="Outstanding" value={money(due)} icon={Clock3}/><Stat label="Notes available" value={notes.length} icon={BookOpen}/><Stat label="Unread alerts" value={notifications.filter(n=>!n.read).length} icon={Bell}/></div><div className="grid-2"><Card><h3>Batch schedule</h3><BatchInfo batchId={profile.batchId}/></Card><Card><h3>Recent notifications</h3>{notifications.sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).slice(0,4).map(n=><div className="list-row" key={n.id}><div><strong>{n.title}</strong><small>{n.message}</small></div></div>)}{!notifications.length&&<Empty>No notifications.</Empty>}</Card></div></>}
function BatchInfo({batchId}){const [b,setB]=React.useState(null);React.useEffect(()=>{getDoc(doc(db,'batches',batchId)).then(s=>s.exists()&&setB(s.data()))},[batchId]);return b?<div className="batch-info"><p><b>Days:</b> {b.days}</p><p><b>Timing:</b> {b.timing}</p><p><b>Fee:</b> {money(b.fee)}</p></div>:<p>Loading schedule…</p>}
function StudentFees({fees,profile}){const year=new Date().getFullYear();return <Card><div className="section-title"><div><h3>{year} annual fee ledger</h3><p>Payment processing is currently under maintenance.</p></div><Button variant="secondary" onClick={()=>alert('Online payment is under maintenance.')}>Pay now</Button></div><div className="months-grid student">{months.map((m,i)=>{const f=fees.find(x=>x.year===year&&x.month===i+1);const future=i+1>new Date().getMonth()+1&&!f;const status=f?.status||(future?'upcoming':'due');return <div className="month" key={m}><strong>{m}</strong><span className={`pill ${status}`}>{status}</span><small>{money(f?.amount||profile.monthlyFee)}</small>{f?.paidAt&&<small>Paid {dateText(f.paidAt)}</small>}</div>})}</div></Card>}
function StudentNotes({notes,notify}){async function open(n){try{const x=await api('/api/storage/sign-download',{method:'POST',body:JSON.stringify({path:n.filePath,noteId:n.id})});window.open(x.url,'_blank','noopener,noreferrer')}catch(e){notify({type:'error',text:e.message})}}return <div className="notes-grid">{notes.map(n=><Card key={n.id} className="note-card"><BookOpen size={32}/><h3>{n.title}</h3><p>{n.fileName}</p><Button onClick={()=>open(n)}><ExternalLink size={17}/> Open PDF</Button></Card>)}{!notes.length&&<Empty>No notes have been uploaded for your batch.</Empty>}</div>}
function StudentNotifications({notifications}){const sorted=[...notifications].sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));return <div className="cards-list">{sorted.map(n=><Card key={n.id} className={!n.read?'unread':''} onClick={()=>!n.read&&updateDoc(doc(db,'notifications',n.id),{read:true})}><div className="section-title"><div><h3>{n.title}</h3><p>{dateText(n.createdAt)}</p></div>{!n.read&&<span className="new-dot">New</span>}</div><p>{n.message}</p></Card>)}{!sorted.length&&<Empty>No notifications.</Empty>}</div>}
function StudentDoubts({profile,doubts,notify}){const [description,setDescription]=React.useState(''),[file,setFile]=React.useState(null),[busy,setBusy]=React.useState(false);async function submit(e){e.preventDefault();setBusy(true);try{let imagePath='',imageName='';if(file){if(!supabase)throw new Error(supabaseClientError);const signed=await api('/api/storage/sign-upload',{method:'POST',body:JSON.stringify({fileName:file.name,mimeType:file.type,size:file.size,type:'doubt'})});const {error}=await supabase.storage.from(bucket).uploadToSignedUrl(signed.path,signed.token,file,{contentType:file.type});if(error)throw new Error(error.message);imagePath=signed.path;imageName=file.name;}await addDoc(collection(db,'doubts'),{studentUid:profile.id,studentName:profile.name,batchId:profile.batchId,batchName:profile.batchName,description,imagePath,imageName,status:'pending',answer:'',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});setDescription('');setFile(null);e.target.reset();notify({type:'success',text:'Doubt submitted.'})}catch(e){notify({type:'error',text:e.message})}finally{setBusy(false)}}return <div className="grid-form"><Card><h3>Ask your chemistry doubt</h3><form onSubmit={submit} className="form-grid"><Textarea label="Describe your question" rows="6" value={description} onChange={e=>setDescription(e.target.value)} required/><label className="upload-box"><Upload/><span>{file?.name||'Attach an image (optional)'}</span><input type="file" accept="image/*" onChange={e=>setFile(e.target.files[0])}/></label><Button disabled={busy}>{busy?'Submitting…':'Submit doubt'}</Button></form></Card><Card><h3>Your doubts</h3>{doubts.map(d=><div className="doubt-mini" key={d.id}><div><strong>{d.description}</strong><small>{dateText(d.createdAt)}</small></div><span className={`pill ${d.status}`}>{d.status}</span>{d.answer&&<p><b>Teacher:</b> {d.answer}</p>}</div>)}{!doubts.length&&<Empty>You have not submitted any doubts.</Empty>}</Card></div>}
function Calendar({profile}){const now=new Date(),days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate(),first=new Date(now.getFullYear(),now.getMonth(),1).getDay();return <Card><div className="section-title"><div><h3>{now.toLocaleString('en-IN',{month:'long',year:'numeric'})}</h3><p>{profile.batchName}</p></div></div><div className="calendar-grid">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=><b key={x}>{x}</b>)}{Array(first).fill(0).map((_,i)=><span key={`e${i}`}/>)}{Array.from({length:days},(_,i)=>i+1).map(d=><span className={d===now.getDate()?'today':''} key={d}>{d}</span>)}</div><div className="calendar-note"><Clock3/> Check the dashboard for your batch timing and class days.</div></Card>}
export default App;
